development:
  adapter: postgresql
  encoding: unicode
  database: shop_development
  pool: 5
  username: boaz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: boaz
  password:

