# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47996fe5cea3545d6a4d538522a1ab015ad86f4c7e58b2fdccc3231d16731e25b0e4b7c3fa2e31adbf7e39f59339ec8b931d6b7ab226551a84cc7857d74a2ba0

test:
  secret_key_base: f0eccbd2630dd65970d3246f4e59611562531d6d34d0979720ffcadd18083e90312a98cbfbd6cdcafde7e780e7d486f067167d79f9409d5da398b71751686ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
